# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=500)),
                ('hr_spent', models.DurationField(default=0)),
                ('current_state', models.IntegerField(choices=[(1, 'Not Started'), (2, 'Dev'), (3, 'QA'), (4, 'Build'), (5, 'Deployment'), (6, 'Others')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.IntegerField(choices=[(1, 'Jira Ticket'), (2, 'Learning'), (3, 'Training'), (4, 'Internal Product'), (5, 'Other')])),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('due_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'Completed'), (3, 'In-Process'), (4, 'Under-Review')])),
                ('assigned_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='milestone',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
